Invoicing edit
GonzaloMCG/ProyectoEmpresas pull request #23
Opened 2021-05-14 04:00 UTC by GonzaloMCG

2021-05-14 17:36 UTC, ceciDucos requested changes
muy prolijo :clap:

2021-05-14 17:36 UTC, ceciDucos commented on facturacion-web/src/app/landing/invoicing-page/invoicing-page.component.html
> +    <div class="blue-div">
```suggestion
    <div class="blue-container">
```

2021-05-14 17:36 UTC, ceciDucos commented on facturacion-web/src/app/landing/invoicing-page/invoicing-page.component.html
> +      <div class="blue-label">
```suggestion
      <div class="sub-title">
```
en todos los lugares donde se repite

2021-05-14 17:36 UTC, ceciDucos commented on facturacion-web/src/app/landing/invoicing-page/invoicing-page.component.scss
> +  user-select:none;
esto qué hace?

2021-05-14 17:36 UTC, ceciDucos commented on facturacion-web/src/app/landing/invoicing-page/invoicing-page.component.scss
> +.blue-div{
```suggestion
.blue-container {
```

2021-05-14 17:36 UTC, ceciDucos commented on facturacion-web/src/app/landing/invoicing-page/invoicing-page.component.scss
> +  cursor:context-menu;
`cursor:context-menu;` para qué lo utilizas?

2021-05-14 17:36 UTC, ceciDucos commented on facturacion-web/src/app/landing/invoicing-page/invoicing-page.component.scss
> +  user-select:none;
me parece que esto no es necesario

2021-05-14 17:36 UTC, ceciDucos commented on facturacion-web/src/app/landing/invoicing-page/invoicing-page.component.scss
> +  user-select:none;
esto está en todos lados

2021-05-14 23:03 UTC, GonzaloMCG commented on facturacion-web/src/app/landing/invoicing-page/invoicing-page.component.scss
> +  user-select:none;
No permite seleccionar el texto para copiarlo, no se pinta de azul

2021-05-14 23:37 UTC, GonzaloMCG commented on facturacion-web/src/app/landing/invoicing-page/invoicing-page.component.scss
> +  cursor:context-menu;
No permite seleccionar el texto

2021-05-14 23:39 UTC, GonzaloMCG commented on facturacion-web/src/app/landing/invoicing-page/invoicing-page.component.scss
> +  user-select:none;
es peor que la mugre XD

2021-05-14 23:40 UTC, GonzaloMCG commented on facturacion-web/src/app/landing/invoicing-page/invoicing-page.component.scss
> +  user-select:none;
No permite seleccionar texto arrastrando con el mouse

2021-05-15 00:50 UTC, ceciDucos approved these changes

2021-05-15 11:23 UTC, merged