List and register users || Stock Page
GonzaloMCG/ProyectoEmpresas pull request #35
Opened 2021-05-17 21:51 UTC by GonzaloMCG

2021-05-17 22:55 UTC, GonzaloMCG commented
General:
Validar forms de todos los modal
mensajes de error
imprimir factura

Admin page:
ocultar tabla de usuarios en página de admin según rol
Cambiar contraseña de usuario propio

2021-05-18 00:21 UTC, ceciDucos requested changes

2021-05-18 00:21 UTC, ceciDucos commented on facturacion-web/src/app/landing/admin-page/admin-page.component.html
> +        <!--<td mat-cell *matCellDef="let articulo"> {{articulo.user}} </td>-->
```suggestion
```

2021-05-18 00:21 UTC, ceciDucos commented on facturacion-web/src/app/landing/admin-page/admin-page.component.html
> +        <!--<td mat-cell *matCellDef="let articulo"> {{articulo.rol}} </td>-->
```suggestion
```

2021-05-18 00:21 UTC, ceciDucos commented on facturacion-web/src/app/landing/admin-page/admin-page.component.ts
>          //si le diste cerrar con el aceptar, hacemos algo
```suggestion
```

2021-05-18 00:21 UTC, ceciDucos commented on facturacion-web/src/app/landing/admin-page/admin-page.component.ts
> +    console.log(user);
```suggestion
```

2021-05-18 00:21 UTC, ceciDucos commented on facturacion-web/src/app/landing/admin-page/admin-page.component.ts
>          //si le diste cerrar con el aceptar, hacemos algo
```suggestion
```

2021-05-18 00:21 UTC, ceciDucos commented on facturacion-web/src/app/landing/admin-page/admin-page.component.ts
>          //si le diste cerrar con el aceptar, hacemos algo
```suggestion
```

2021-05-18 00:21 UTC, ceciDucos commented on facturacion-web/src/app/landing/modals/add-product-modal/add-product-modal.component.ts
> +    }
```suggestion
```

2021-05-18 00:21 UTC, ceciDucos commented on facturacion-web/src/app/landing/modals/add-product-modal/add-product-modal.component.ts
> +        console.log('cierra');
```suggestion
```

2021-05-18 00:21 UTC, ceciDucos commented on facturacion-web/src/app/landing/modals/add-product-modal/add-product-modal.component.ts
> +        console.log('cierra');
```suggestion
```

2021-05-18 00:21 UTC, ceciDucos commented on facturacion-web/src/app/landing/modals/add-user-modal/add-user-modal.component.html
> +          <!--<input id="name" class="input input-user" type="text" autocomplete="off">-->
```suggestion
```

2021-05-18 00:21 UTC, ceciDucos commented on facturacion-web/src/app/landing/modals/delete-item-modal/delete-item-modal.component.ts
> +        console.log('cierra');
```suggestion
```

2021-05-18 00:21 UTC, ceciDucos commented on facturacion-web/src/app/landing/modals/delete-item-modal/delete-item-modal.component.ts
> +        console.log('cierra');
```suggestion
```

2021-05-18 00:21 UTC, ceciDucos commented on facturacion-web/src/app/landing/modals/delete-item-modal/delete-item-modal.component.ts
> +      console.log(error);
```suggestion
```

2021-05-18 00:21 UTC, ceciDucos commented on facturacion-web/src/app/landing/modals/edit-user-modal/edit-user-modal.component.ts
> +        console.log(error);
```suggestion
```

2021-05-18 00:21 UTC, ceciDucos commented on facturacion-web/src/app/landing/stock-page/stock-page.component.ts
> +      console.log(error);
```suggestion
```

2021-05-18 00:21 UTC, ceciDucos commented on facturacion-web/src/app/services/product.service.ts
> +    /*if (!productList) {
```suggestion
```

2021-05-18 00:21 UTC, ceciDucos commented on facturacion-web/src/app/services/product.service.ts
> +    }*/
```suggestion
```

2021-05-18 00:21 UTC, ceciDucos commented on facturacion-web/src/app/services/user.service.ts
> +    //const headers = this.authenticationService.getHeaders();
```suggestion
```

2021-05-18 00:21 UTC, ceciDucos commented on facturacion-web/src/app/services/user.service.ts
> +    console.log(data);
```suggestion
```

2021-05-18 00:21 UTC, ceciDucos commented on facturacion-web/src/app/services/user.service.ts
> +
```suggestion
```

2021-05-18 00:21 UTC, ceciDucos commented on facturacion-web/src/app/services/user.service.ts
> +    console.log(data);
```suggestion
```

2021-05-18 00:38 UTC, ceciDucos approved these changes

2021-05-18 00:39 UTC, merged