More validators
GonzaloMCG/ProyectoEmpresas pull request #46
Opened 2021-05-23 06:32 UTC by fp90

2021-05-23 21:10 UTC, ceciDucos commented on facturacion-web/src/app/landing/admin-page/admin-page.component.ts
> +    if (this.paginator) {
esto lo pusiste por algo en particular?

2021-05-23 21:15 UTC, ceciDucos commented on facturacion-web/src/app/landing/invoicing-page/invoicing-page.component.html
> +          {{product.name}} ({{product.stock}})
:clap: :clap: :clap:

2021-05-23 21:16 UTC, ceciDucos commented on facturacion-web/src/app/landing/invoicing-page/invoicing-page.component.html
> +    <button class="button" (click)="cleanInvoice()">
:clap: :clap: :clap:

2021-05-23 21:24 UTC, ceciDucos requested changes

2021-05-23 21:24 UTC, ceciDucos commented on facturacion-web/src/app/landing/modals/add-user-modal/add-user-modal.component.html
> +              No puede ser vacio.
```suggestion
              No puede ser vacío.
```

2021-05-23 21:24 UTC, ceciDucos commented on facturacion-web/src/app/landing/modals/add-user-modal/add-user-modal.component.html
> +              Los passwords no coinciden.
```suggestion
             Las contraseñas no coinciden.
```

2021-05-23 21:24 UTC, ceciDucos commented on facturacion-web/src/app/landing/modals/add-product-modal/add-product-modal.component.html
>                  No puede ser vacio.
```suggestion
                No puede ser vacío.
```

2021-05-23 21:24 UTC, ceciDucos commented on facturacion-web/src/app/landing/modals/add-product-modal/add-product-modal.component.html
>                  No puede ser vacio.
```suggestion
                No puede ser vacío.
```

2021-05-23 21:24 UTC, ceciDucos commented on facturacion-web/src/app/landing/modals/add-user-modal/add-user-modal.component.html
> +              Debe contener al menos un numero.
```suggestion
              Debe contener al menos un número.
```

2021-05-23 21:24 UTC, ceciDucos commented on facturacion-web/src/app/landing/modals/add-user-modal/add-user-modal.component.html
> +              Debe contener al menos una mayuscula.
```suggestion
              Debe contener al menos una mayúscula.
```

2021-05-23 21:24 UTC, ceciDucos commented on facturacion-web/src/app/landing/modals/add-user-modal/add-user-modal.component.html
> +              Debe contener al menos una minuscula.
```suggestion
              Debe contener al menos una minúscula.
```

2021-05-23 21:24 UTC, ceciDucos commented on facturacion-web/src/app/landing/modals/edit-invoice-product-modal/edit-invoice-product-modal.component.html
> +              No puede ser vacio.
```suggestion
              No puede ser vacío.
```

2021-05-23 21:24 UTC, ceciDucos commented on facturacion-web/src/app/landing/modals/edit-invoice-product-modal/edit-invoice-product-modal.component.html
> +              No puede ser vacio.
```suggestion
              No puede ser vacío.
```

2021-05-23 21:24 UTC, ceciDucos commented on facturacion-web/src/app/landing/modals/edit-invoice-product-modal/edit-invoice-product-modal.component.html
> +              No puede ser vacio.
```suggestion
              No puede ser vacío.
```

2021-05-23 21:24 UTC, ceciDucos commented on facturacion-web/src/app/message-handler/message.service.ts
> -    console.log('message: ');
Gracias!!

2021-05-23 21:24 UTC, ceciDucos commented on facturacion-web/src/app/message-handler/message.service.ts
> +        return 'No tiene permisos para acceder o su sesion expiro, por favor loguearse.';
```suggestion
        return 'No tiene permisos para acceder o su sesión expiro, por favor loguearse.';
```

2021-05-24 00:14 UTC, fp90 commented on facturacion-web/src/app/landing/admin-page/admin-page.component.ts
> +    if (this.paginator) {
porque para los usuarios no Administador intenta cargar la tabla de usuarios que no existe sino y daba unos errores en el navegador

2021-05-24 00:16 UTC, ceciDucos approved these changes

2021-05-24 00:24 UTC, merged